name: "dbt_fundamentals_on_demand"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_fundamentals_on_demand:
    staging:
      +materialized: view
    marts:
      +materialized: table